### ISSUE TITLE
Marking successful requests as failed

### ISSUE THREAD

**Issue by LunaticoCR** [schminkel/insomnia-plugin-run-all-requests#1]
I just installed this plugin today and ran the requests in a folder and it is marking successful 200OK responses as failures.

![image](https://github.com/schminkel/insomnia-plugin-run-all-requests/assets/2124383/a73646aa-e336-4a7b-9c8c-78f43ee404ec)

**Comment by schminkel** [comment]
Hi, you need to add "[200]" to the end of the request name to make the validation work!
see here: 
https://insomnia.rest/plugins/insomnia-plugin-run-all-requests
...
In addition, the plugin validates the response code of each request, and displays a warning if any of the request results do not match the expected response code. To configure the expected response code, add the response code to the request name in brackets, e.g. Get User [200]. If the response code of the request does not match the expected response code from the name, the request will be marked with 'Failed' in the list.
...

**Comment by LunaticoCR** [comment]
Oh, got it! Could I suggest that in the absence of a [xxx] value the default should be marking responses with an http status of 200-299 as success?
